# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: textToSpeechify

permissions:
  contents: read

on:
  workflow_dispatch: 
  
  push:
    branches: 
    - main

jobs:
  regression-test-ubuntu:

    strategy:
        matrix:
          version: ["3.7", "3.8", "3.9", "3.10"]
          os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - name: Install pdftohtml
      run: |
        sudo apt-get update
        sudo apt-get install poppler-utils
    - name: Install textToSpeechifyTester dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run textToSpeechifyTester
      run: |
        cd tests
        python textToSpeechifyTester.py

  regression-test-macos:

    strategy:
        matrix:
          version: ["3.7", "3.8", "3.9", "3.10"]
          os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}

    - name: Install pdftohtml
      run: |
        brew update
        brew install pdftohtml

    - name: Install textToSpeechifyTester dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run textToSpeechifyTester
      run: |
        cd tests
        python textToSpeechifyTester.py

  regression-test-windows:

    strategy:
        matrix:
          version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
    env:
        PYTHONIOENCODING: utf-8
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}

    - name: Install textToSpeechifyTester dependencies
      run: |
        py -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run textToSpeechifyTester
      run: |
        cd tests
        py -3 textToSpeechifyTester.py 
